version: '3.5'
services:

  suricata:
    #build: ./${OS_SURICATA}/Dockerfile/
    build: ./alpine/Dockerfile/
    #image: jasonish/suricata:latest
    container_name: suricata
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW  
    volumes:
      - ./alpine/Dockerfile/suricata.yaml:/etc/suricata/suricata.yaml
      - ./alpine/Dockerfile/classification.config:/etc/suricata/classification.config
      - /var/log/suricata:/var/log/suricata
      - ./rules/sensible-topic.rules:/var/lib/suricata/rules/sensible-topic.rules
      - ./rules/information-grabber.rules:/var/lib/suricata/rules/information-grabber.rules
      - ./rules/bruteforce.rules:/var/lib/suricata/rules/bruteforce.rules
      - ./rules/c2.rules:/var/lib/suricata/rules/c2.rules
      - ./alpine/Dockerfile/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./alpine/Dockerfile/password.txt:/etc/mosquitto/password.txt
      - ./alpine/Dockerfile/password-clear.txt:/etc/mosquitto/password-clear.txt
      - ./malware:/tmp/malware
    #entrypoint: /tmp/docker-entrypoint.sh
    # command: -i eth0
    command: -q 0
    ports:
      - 3000:3000
      - 1883:1883
      - 9000:9000
    networks:
      mynetwork:
        ipv4_address: 172.21.0.2
        
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
