version: '3.5'
services:
  suricata:
    image: eevalente/mosquitto-suricata:1.0.0
    container_name: mosquitto-suricata
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW  
    volumes:
      - ./suricata-files/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata-files/classification.config:/etc/suricata/classification.config
      - ./suricata-files/rules/my.rules:/var/lib/suricata/rules/my.rules
      - /var/log/suricata:/var/log/suricata
      - ./mosquitto-files/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto-files/password.txt:/etc/mosquitto/password.txt
      - ./mosquitto-files/password-clear.txt:/etc/mosquitto/password-clear.txt

    command: -q 0
    ports:
      - 1883:1883
    networks:
      mynetwork:
        ipv4_address: 172.21.0.2
        
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
